name: Upload Software to TIRA

on:
  workflow_dispatch:  # 👈 Enables manual "Run workflow" button

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install TIRA
      run: pip install tira

    - name: Build Docker Image
      run: |
        docker build -t registry.webis.de/code-research/tira/tira-user-pirate-passau/tira-submission:0.0.1 -f Dockerfile .

    - name: Push to TIRA
      run: tira-run --input-dataset=advertisement-in-retrieval-augmented-generation-2025/ads-in-rag-task-2-classification-spot-check --image=registry.webis.de/code-research/tira/tira-user-pirate-passau/tira-submission:0.0.1 --push