name: Upload to TIRA

on:
  push:
    branches: [main]  # or 'master' depending on your default branch

jobs:
  upload-to-tira:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install tira

    - name: Login to Docker (if required)
      run: echo "Skip if not using private repo or auth needed"

    - name: Build Docker Image
      run: docker build -t registry.webis.de/code-research/tira/YOUR-IMAGE-NAME:0.0.1 -f Dockerfile .

    - name: Push to TIRA
      run: |
        tira-run \
          --input-dataset advertisement-in-retrieval-augmented-generation-2025/ads-in-rag-task-2-classification-spot-check-20250423_1-training \
          --image registry.webis.de/code-research/tira/YOUR-IMAGE-NAME:0.0.1
